# https://stackoverflow.com/questions/60180630/lerna-always-lists-all-packages-ready-to-publish-when-running-workflow-of-github

name: Publish changed packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      # Required for OIDC (https://docs.npmjs.com/trusted-publishers#github-actions-configuration)
      id-token: write
     
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        # clone all git-repo with full history, not only last commit. it needs for correct lerna work 
        # https://github.com/lerna/lerna/issues/2542
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: '@tourmalinecore'

      - name: Install dependencies
        run: npm ci

      # https://lerna.js.org/docs/features/version-and-publish#from-package
      - name: Publish changed packages
        run: |
          npx lerna publish from-package --yes
