name: Publish changed packages

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        # clone all git-repo with full history, not only last commit. it needs for correct lerna work 
        # https://github.com/lerna/lerna/issues/2542
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Publish changed packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx lerna publish --yes
