# https://stackoverflow.com/questions/60180630/lerna-always-lists-all-packages-ready-to-publish-when-running-workflow-of-github

name: Publish changed packages

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        # clone all git-repo with full history, not only last commit. it needs for correct lerna work 
        # https://github.com/lerna/lerna/issues/2542
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Fetch tags
        run: git fetch --tags

      - name: Publish changed packages
        env:
          ACTIONS_NPM_PUBLISH_ACCESS_TOKEN: ${{ secrets.ACTIONS_NPM_PUBLISH_ACCESS_TOKEN }}
        # flag from-git helps to retry failed pubication
        # https://lerna.js.org/docs/faq#:~:text=%D0%B2%D0%B0%D1%88%D0%B5%D0%B9%20%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%BE%D0%B9%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5.-,%D0%9A%D0%B0%D0%BA%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D1%82%D1%8C%20%D0%BF%D0%BE%D0%BF%D1%8B%D1%82%D0%BA%D1%83%20%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B8%20%D0%B2%20%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B5%20publish%D0%BD%D0%B5%D1%83%D0%B4%D0%B0%D1%87%D0%B8,-%3F
        # https://github.com/lerna/lerna/pull/3513
        run: |
          npx lerna publish from-git --yes
